[package]
name = "uclcli-reborn"
version = "0.2.0"
authors = ["Andrew Rogoff <andrew@andrewbrogoff.com>"]
edition = "2024"
rust-version = "1.92"
description = "command line compressor/decompressor using libucl / NRV (fork of afflux/uclcli)"
repository = "https://github.com/andrewbrogoff/uclcli-reborn/"
license = "GPL-3.0-or-later"
links = "ucl"

[lib]
name = "uclcli"

[dependencies]
clap = { version = "4", features = ["derive"] }
libc = "0.2"
memmap2 = "0.9"
anyhow = "1.0"
thiserror = "2.0"

[[bin]]
name = "ucl"
path = "src/bin/ucl.rs"

[[bin]]
name = "unucl"
path = "src/bin/unucl.rs"
