
[package]
name = "uclcli-fuzz"
version = "0.0.0"
authors = ["Andrew Rogoff <andrew@andrewbrogoff.com>"]
publish = false
edition = "2024"
license = "GPL-3.0-or-later"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
uclcli = { package = "uclcli-reborn", path = ".." }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "compress"
path = "fuzz_targets/compress.rs"
test = false
doc = false

[[bin]]
name = "decompress"
path = "fuzz_targets/decompress.rs"
test = false
doc = false
